In [1]:
from src.data_pipeline.loaders.loaders import load_har_dataset
from src.training.scripts.training import train_model_lstm
from src.models.lstm import LSTM
import torch
import torch.nn as nn
import numpy as np

In [2]:
dataset_path = "./../../data/raw/HAR/"
resize_dataset_video_path = "./../../data/processed/HAR/"
output_csv_path = "./../../data/processed/HAR/UCF"

In [3]:


test = np.array([np.nan, np.nan, np.nan], dtype=np.float32)
print(np.isnan(test).all())

x_train, y_train = load_har_dataset(dataset_path,
                                    resize_dataset_video_path,
                                    output_csv_path,
                                    max_dim=35, train_test='train')

# check nan values
print(f"Training data shape: {x_train.shape}, Training labels shape: {y_train.shape}")
for i in range(x_train.shape[0]):
    if np.isnan(x_train[i]).any():
        print(f'X_train nan values in {i}th row')
        print(x_train[i])
        break

True
Loading data from saved numpy arrays
Training data shape: (396, 35, 75, 3), Training labels shape: (396,)
X_train nan values in 12th row
[[[ 0.51518035  0.3186636  -0.31946817]
  [ 0.5221733   0.30450466 -0.31405962]
  [ 0.5264187   0.30406633 -0.31411478]
  ...
  [        nan         nan         nan]
  [        nan         nan         nan]
  [        nan         nan         nan]]

 [[ 0.5140137   0.31891584 -0.3386466 ]
  [ 0.52171725  0.3047338  -0.3340165 ]
  [ 0.5259264   0.30429608 -0.33403373]
  ...
  [        nan         nan         nan]
  [        nan         nan         nan]
  [        nan         nan         nan]]

 [[ 0.5150263   0.31876394 -0.3432704 ]
  [ 0.5224237   0.30492434 -0.33709446]
  [ 0.526701    0.30456045 -0.33711678]
  ...
  [        nan         nan         nan]
  [        nan         nan         nan]
  [        nan         nan         nan]]

 ...

 [[ 0.51757383  0.3174985  -0.34759152]
  [ 0.5254659   0.30327812 -0.33929625]
  [ 0.53000057  0.30309516 -

In [8]:
x_train[12][2]

array([[ 5.15026271e-01,  3.18763942e-01, -3.43270391e-01],
       [ 5.22423685e-01,  3.04924339e-01, -3.37094456e-01],
       [ 5.26700974e-01,  3.04560453e-01, -3.37116778e-01],
       [ 5.30886471e-01,  3.04340303e-01, -3.37284148e-01],
       [ 5.13585925e-01,  3.05410236e-01, -3.10378581e-01],
       [ 5.11630118e-01,  3.05247426e-01, -3.10270488e-01],
       [ 5.10113597e-01,  3.05076450e-01, -3.10325056e-01],
       [ 5.41862905e-01,  3.09232086e-01, -2.57762074e-01],
       [ 5.16213715e-01,  3.09874594e-01, -1.40592769e-01],
       [ 5.23941219e-01,  3.32107991e-01, -3.11101705e-01],
       [ 5.13516247e-01,  3.31718951e-01, -2.77341664e-01],
       [ 5.64183354e-01,  3.84729207e-01, -3.21943283e-01],
       [ 5.20664811e-01,  3.99597287e-01,  7.45011121e-02],
       [ 5.65626562e-01,  4.98864114e-01, -3.59056771e-01],
       [ 5.08750260e-01,  5.06456614e-01,  1.55663759e-01],
       [ 5.49085319e-01,  6.13499582e-01, -3.81228864e-01],
       [ 5.11951387e-01,  6.04197919e-01